/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMoodRouteImport } from './routes/_authenticated/mood'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedResourcesIndexRouteImport } from './routes/_authenticated/resources/index'
import { Route as AuthHeyhoAuthorizeRouteImport } from './routes/auth/heyho/authorize'
import { Route as AuthenticatedResourcesCategoryRouteImport } from './routes/_authenticated/resources/$category'
import { Route as AuthenticatedJournalNewRouteImport } from './routes/_authenticated/journal.new'
import { Route as AuthenticatedJournalIdEditRouteImport } from './routes/_authenticated/journal.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMoodRoute = AuthenticatedMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesIndexRoute =
  AuthenticatedResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthHeyhoAuthorizeRoute = AuthHeyhoAuthorizeRouteImport.update({
  id: '/auth/heyho/authorize',
  path: '/auth/heyho/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResourcesCategoryRoute =
  AuthenticatedResourcesCategoryRouteImport.update({
    id: '/resources/$category',
    path: '/resources/$category',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJournalNewRoute = AuthenticatedJournalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedJournalRoute,
} as any)
const AuthenticatedJournalIdEditRoute =
  AuthenticatedJournalIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedJournalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/journal': typeof AuthenticatedJournalRouteWithChildren
  '/mood': typeof AuthenticatedMoodRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/journal/new': typeof AuthenticatedJournalNewRoute
  '/resources/$category': typeof AuthenticatedResourcesCategoryRoute
  '/auth/heyho/authorize': typeof AuthHeyhoAuthorizeRoute
  '/resources': typeof AuthenticatedResourcesIndexRoute
  '/journal/$id/edit': typeof AuthenticatedJournalIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/journal': typeof AuthenticatedJournalRouteWithChildren
  '/mood': typeof AuthenticatedMoodRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/journal/new': typeof AuthenticatedJournalNewRoute
  '/resources/$category': typeof AuthenticatedResourcesCategoryRoute
  '/auth/heyho/authorize': typeof AuthHeyhoAuthorizeRoute
  '/resources': typeof AuthenticatedResourcesIndexRoute
  '/journal/$id/edit': typeof AuthenticatedJournalIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRouteWithChildren
  '/_authenticated/mood': typeof AuthenticatedMoodRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/journal/new': typeof AuthenticatedJournalNewRoute
  '/_authenticated/resources/$category': typeof AuthenticatedResourcesCategoryRoute
  '/auth/heyho/authorize': typeof AuthHeyhoAuthorizeRoute
  '/_authenticated/resources/': typeof AuthenticatedResourcesIndexRoute
  '/_authenticated/journal/$id/edit': typeof AuthenticatedJournalIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/goals'
    | '/habits'
    | '/journal'
    | '/mood'
    | '/settings'
    | '/journal/new'
    | '/resources/$category'
    | '/auth/heyho/authorize'
    | '/resources'
    | '/journal/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/goals'
    | '/habits'
    | '/journal'
    | '/mood'
    | '/settings'
    | '/journal/new'
    | '/resources/$category'
    | '/auth/heyho/authorize'
    | '/resources'
    | '/journal/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/goals'
    | '/_authenticated/habits'
    | '/_authenticated/journal'
    | '/_authenticated/mood'
    | '/_authenticated/settings'
    | '/_authenticated/journal/new'
    | '/_authenticated/resources/$category'
    | '/auth/heyho/authorize'
    | '/_authenticated/resources/'
    | '/_authenticated/journal/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthHeyhoAuthorizeRoute: typeof AuthHeyhoAuthorizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mood': {
      id: '/_authenticated/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof AuthenticatedMoodRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources/': {
      id: '/_authenticated/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/heyho/authorize': {
      id: '/auth/heyho/authorize'
      path: '/auth/heyho/authorize'
      fullPath: '/auth/heyho/authorize'
      preLoaderRoute: typeof AuthHeyhoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resources/$category': {
      id: '/_authenticated/resources/$category'
      path: '/resources/$category'
      fullPath: '/resources/$category'
      preLoaderRoute: typeof AuthenticatedResourcesCategoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal/new': {
      id: '/_authenticated/journal/new'
      path: '/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof AuthenticatedJournalNewRouteImport
      parentRoute: typeof AuthenticatedJournalRoute
    }
    '/_authenticated/journal/$id/edit': {
      id: '/_authenticated/journal/$id/edit'
      path: '/$id/edit'
      fullPath: '/journal/$id/edit'
      preLoaderRoute: typeof AuthenticatedJournalIdEditRouteImport
      parentRoute: typeof AuthenticatedJournalRoute
    }
  }
}

interface AuthenticatedJournalRouteChildren {
  AuthenticatedJournalNewRoute: typeof AuthenticatedJournalNewRoute
  AuthenticatedJournalIdEditRoute: typeof AuthenticatedJournalIdEditRoute
}

const AuthenticatedJournalRouteChildren: AuthenticatedJournalRouteChildren = {
  AuthenticatedJournalNewRoute: AuthenticatedJournalNewRoute,
  AuthenticatedJournalIdEditRoute: AuthenticatedJournalIdEditRoute,
}

const AuthenticatedJournalRouteWithChildren =
  AuthenticatedJournalRoute._addFileChildren(AuthenticatedJournalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRouteWithChildren
  AuthenticatedMoodRoute: typeof AuthenticatedMoodRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedResourcesCategoryRoute: typeof AuthenticatedResourcesCategoryRoute
  AuthenticatedResourcesIndexRoute: typeof AuthenticatedResourcesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRouteWithChildren,
  AuthenticatedMoodRoute: AuthenticatedMoodRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedResourcesCategoryRoute: AuthenticatedResourcesCategoryRoute,
  AuthenticatedResourcesIndexRoute: AuthenticatedResourcesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthHeyhoAuthorizeRoute: AuthHeyhoAuthorizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
